language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules/"
after_success:
  - npm run coverage
before_script:
  - npm install -g mocha && npm install -g nyc && npm install coveralls
